In [14]:
#importamos librerías necesarias
import pandas as pd
import requests
import os
from dotenv import load_dotenv
import tarfile
import gzip
import io
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
import time
import re

In [15]:
# cargamos API_KEY
load_dotenv()

API_KEY = os.getenv("AEMET_API_KEY")

if API_KEY is None:
    raise ValueError("No se ha encontrado la API Key. Revisa el archivo .env")
else:
    print("API Key cargada correctamente")

python-dotenv could not parse statement starting at line 2

API Key cargada correctamente

In [17]:
# definimos fechas del proyecto 
fecha_inicio_total = datetime(2021, 1, 1)
fecha_fin_total = datetime(2026, 4, 30)

print("Fecha inicio:", fecha_inicio_total)
print("Fecha fin:", fecha_fin_total)

Fecha inicio: 2021-01-01 00:00:00
Fecha fin: 2026-04-30 00:00:00

In [18]:
# Creamos rango de dos dias para la extracción de datos
rangos_fechas = []

fecha_actual = fecha_inicio_total

while fecha_actual <= fecha_fin_total:
    inicio = fecha_actual
    fin = min(fecha_actual + timedelta(days=1), fecha_fin_total)

    rangos_fechas.append((inicio, fin))

    fecha_actual = fin + timedelta(days=1)

print("Número de rangos creados:", len(rangos_fechas))

for inicio, fin in rangos_fechas[:10]:
    print(inicio.strftime("%Y-%m-%d"), "→", fin.strftime("%Y-%m-%d"))

print("...")

for inicio, fin in rangos_fechas[-10:]:
    print(inicio.strftime("%Y-%m-%d"), "→", fin.strftime("%Y-%m-%d"))

Número de rangos creados: 973
2021-01-01 → 2021-01-02
2021-01-03 → 2021-01-04
2021-01-05 → 2021-01-06
2021-01-07 → 2021-01-08
2021-01-09 → 2021-01-10
2021-01-11 → 2021-01-12
2021-01-13 → 2021-01-14
2021-01-15 → 2021-01-16
2021-01-17 → 2021-01-18
2021-01-19 → 2021-01-20
...
2026-04-11 → 2026-04-12
2026-04-13 → 2026-04-14
2026-04-15 → 2026-04-16
2026-04-17 → 2026-04-18
2026-04-19 → 2026-04-20
2026-04-21 → 2026-04-22
2026-04-23 → 2026-04-24
2026-04-25 → 2026-04-26
2026-04-27 → 2026-04-28
2026-04-29 → 2026-04-30

In [19]:
# funciones auxiliares para leer el XML de AEMET
def limpiar_tag(tag):
    if "}" in tag:
        return tag.split("}", 1)[1]
    return tag


def hijos(elemento, nombre):
    return [hijo for hijo in list(elemento) if limpiar_tag(hijo.tag) == nombre]


def texto(elemento, nombre):
    for hijo in list(elemento):
        if limpiar_tag(hijo.tag) == nombre:
            return hijo.text if hijo.text is not None else ""
    return ""

In [20]:
#funciones para descargar un rango de 2 dias 
def descargar_rango_aemet(fecha_inicio, fecha_fin, api_key, pausa=10, max_intentos=5):
    fecha_ini = fecha_inicio.strftime("%Y-%m-%dT00:00:00UTC")
    fecha_fin_str = fecha_fin.strftime("%Y-%m-%dT23:59:59UTC")

    url = (
        "https://opendata.aemet.es/opendata/api/avisos_cap/archivo/"
        f"fechaini/{fecha_ini}/fechafin/{fecha_fin_str}"
    )

    params = {
        "api_key": API_KEY
    }

    for intento in range(1, max_intentos + 1):
        print(f"Intento {intento}/{max_intentos}: {fecha_ini} → {fecha_fin_str}")

        # Primera llamada: pedir a AEMET la URL temporal
        response = requests.get(url, params=params, timeout=90)

        if response.status_code == 429:
            print("Demasiadas peticiones. Esperando 90 segundos...")
            time.sleep(90)
            continue

        if response.status_code != 200:
            print("Error en primera petición:", response.status_code)
            print(response.text[:500])
            time.sleep(pausa)
            continue

        try:
            respuesta_json = response.json()
        except Exception:
            print("La respuesta no es JSON")
            print(response.text[:500])
            time.sleep(pausa)
            continue

        url_datos = respuesta_json.get("datos")

        if not url_datos:
            print("No se encontró URL de datos")
            print(respuesta_json)
            time.sleep(pausa)
            continue

        time.sleep(pausa)

        # Segunda llamada: descargar el archivo real
        datos_response = requests.get(url_datos)

        if datos_response.status_code == 429:
            print("Demasiadas peticiones en descarga. Esperando 90 segundos...")
            time.sleep(90)
            continue

        if datos_response.status_code == 500:
            print("Error 500 en AEMET. Esperando y reintentando...")
            time.sleep(60)
            continue

        if datos_response.status_code != 200:
            print("Error descargando archivo real:", datos_response.status_code)
            print(datos_response.text[:500])
            time.sleep(pausa)
            continue

        contenido = datos_response.content

        # Comprobación mínima: parece TAR si empieza con nombre de archivo Z_CAP...
        if not contenido.startswith(b"Z_CAP"):
            print("El contenido descargado no parece el archivo esperado.")
            print(contenido[:300])
            time.sleep(pausa)
            continue

        print("Descarga correcta")
        return contenido

    print("No se pudo descargar este rango después de varios intentos.")
    return None

In [21]:
# Función para convertir TAR + GZ + XML en tabla
def convertir_contenido_a_dataframe(contenido):
    filas = []

    try:
        archivo_tar = tarfile.open(fileobj=io.BytesIO(contenido), mode="r:")
    except tarfile.TarError:
        print("No se pudo abrir como TAR")
        return pd.DataFrame()

    for miembro in archivo_tar.getmembers():

        if not miembro.name.endswith(".gz"):
            continue

        archivo_extraido = archivo_tar.extractfile(miembro)

        if archivo_extraido is None:
            continue

        contenido_gz = archivo_extraido.read()

        try:
            contenido_xml = gzip.decompress(contenido_gz)
        except gzip.BadGzipFile:
            continue

        texto_xml = contenido_xml.decode("utf-8", errors="ignore")

        bloques_xml = re.findall(
            r"<\?xml.*?</alert>",
            texto_xml,
            flags=re.DOTALL
        )

        for bloque in bloques_xml:

            try:
                root = ET.fromstring(bloque)
            except ET.ParseError:
                continue

            if limpiar_tag(root.tag) == "alert":
                alertas = [root]
            else:
                alertas = [
                    elem for elem in root.iter()
                    if limpiar_tag(elem.tag) == "alert"
                ]

            for alert in alertas:

                identifier = texto(alert, "identifier")
                sender = texto(alert, "sender")
                sent = texto(alert, "sent")
                status = texto(alert, "status")
                msg_type = texto(alert, "msgType")
                scope = texto(alert, "scope")

                for info in hijos(alert, "info"):

                    language = texto(info, "language")
                    category = texto(info, "category")
                    event = texto(info, "event")
                    urgency = texto(info, "urgency")
                    severity = texto(info, "severity")
                    certainty = texto(info, "certainty")
                    effective = texto(info, "effective")
                    onset = texto(info, "onset")
                    expires = texto(info, "expires")
                    headline = texto(info, "headline")
                    description = texto(info, "description")

                    areas = hijos(info, "area")

                    for area in areas:

                        area_desc = texto(area, "areaDesc")
                        polygon = texto(area, "polygon")
                        circle = texto(area, "circle")

                        geocode_valores = []

                        for geocode in hijos(area, "geocode"):
                            value_name = texto(geocode, "valueName")
                            value = texto(geocode, "value")

                            if value_name or value:
                                geocode_valores.append(f"{value_name}: {value}")

                        geocode_texto = " | ".join(geocode_valores)

                        filas.append({
                            "identifier": identifier,
                            "sender": sender,
                            "sent": sent,
                            "status": status,
                            "msg_type": msg_type,
                            "scope": scope,
                            "language": language,
                            "category": category,
                            "event": event,
                            "urgency": urgency,
                            "severity": severity,
                            "certainty": certainty,
                            "effective": effective,
                            "onset": onset,
                            "expires": expires,
                            "headline": headline,
                            "description": description,
                            "area_desc": area_desc,
                            "polygon": polygon,
                            "circle": circle,
                            "geocode": geocode_texto,
                            "archivo_origen": miembro.name
                        })

    return pd.DataFrame(filas)

In [22]:
# funciones para limpiar y crear nuevas columnas 
def limpiar_dataframe(df):
    if df.empty:
        return df

    df_limpio = df.drop_duplicates(
        subset=[
            "identifier",
            "sent",
            "onset",
            "expires",
            "event",
            "severity",
            "area_desc",
            "headline"
        ]
    ).copy()

    # Convertimos fechas usando utc=True para evitar errores con zonas horarias mixtas
    df_limpio["onset"] = pd.to_datetime(df_limpio["onset"], errors="coerce", utc=True)
    df_limpio["expires"] = pd.to_datetime(df_limpio["expires"], errors="coerce", utc=True)
    df_limpio["sent"] = pd.to_datetime(df_limpio["sent"], errors="coerce", utc=True)

    # Creamos año y mes
    df_limpio["año"] = df_limpio["onset"].dt.year
    df_limpio["mes_num"] = df_limpio["onset"].dt.month

    nombres_meses = {
        1: "Enero",
        2: "Febrero",
        3: "Marzo",
        4: "Abril",
        5: "Mayo",
        6: "Junio",
        7: "Julio",
        8: "Agosto",
        9: "Septiembre",
        10: "Octubre",
        11: "Noviembre",
        12: "Diciembre"
    }

    df_limpio["mes"] = df_limpio["mes_num"].map(nombres_meses)

    df_limpio["estacion"] = df_limpio["mes_num"].map({
        12: "Invierno",
        1: "Invierno",
        2: "Invierno",
        3: "Primavera",
        4: "Primavera",
        5: "Primavera",
        6: "Verano",
        7: "Verano",
        8: "Verano",
        9: "Otoño",
        10: "Otoño",
        11: "Otoño"
    })

    df_limpio["duracion_horas"] = (
        df_limpio["expires"] - df_limpio["onset"]
    ).dt.total_seconds() / 3600

    df_limpio["riesgo_numerico"] = df_limpio["severity"].map({
        "Minor": 0,
        "Moderate": 1,
        "Severe": 2,
        "Extreme": 3
    }).fillna(0)

    return df_limpio

In [9]:
# probamos con un solo rango antes que todo 
contenido_prueba = descargar_rango_aemet(
    datetime(2021, 1, 7),
    datetime(2021, 1, 8),
    API_KEY,
    pausa=12
)

df_prueba = convertir_contenido_a_dataframe(contenido_prueba)

df_prueba_limpio = limpiar_dataframe(df_prueba)

print("Filas prueba:", len(df_prueba_limpio))

df_prueba_limpio.head()

Intento 1/5: 2021-01-07T00:00:00UTC → 2021-01-08T23:59:59UTC
Descarga correcta
Filas prueba: 12604

,identifier,sender,sent,status,msg_type,scope,language,category,event,urgency,...,polygon,circle,geocode,archivo_origen,año,mes_num,mes,estacion,duracion_horas,riesgo_numerico
0,2.49.0.0.724.0.ES.20210107043640.750102BTTI070...,http://www.aemet.es,2021-01-07 04:36:40+00:00,Actual,Alert,Public,es-ES,Met,Aviso de temperaturas mínimas de nivel amarillo,Immediate,...,"42.94,-2.98 42.94,-2.93 42.91,-2.86 42.92,-2.7...",,AEMET-Meteoalerta zona: 750102,Z_CAP_C_LEMM_20210107043640_AFAE.gz,2021,1,Enero,Invierno,3.999722,1
1,2.49.0.0.724.0.ES.20210107043640.750102BTTI070...,http://www.aemet.es,2021-01-07 04:36:40+00:00,Actual,Alert,Public,en-GB,Met,Moderate low-temperature warning,Immediate,...,"42.94,-2.98 42.94,-2.93 42.91,-2.86 42.92,-2.7...",,AEMET-Meteoalerta zona: 750102,Z_CAP_C_LEMM_20210107043640_AFAE.gz,2021,1,Enero,Invierno,3.999722,1
2,2.49.0.0.724.0.ES.20210106225001.624401NENV092...,http://www.aemet.es,2021-01-06 22:50:01+00:00,Actual,Alert,Public,es-ES,Met,Aviso de nevadas de nivel naranja,Future,...,"40.94,-1.62 40.94,-1.56 40.96,-1.5 40.96,-1.47...",,AEMET-Meteoalerta zona: 624401,Z_CAP_C_LEMM_20210107043640_AFAE.gz,2021,1,Enero,Invierno,23.999722,2
3,2.49.0.0.724.0.ES.20210106225001.624401NENV092...,http://www.aemet.es,2021-01-06 22:50:01+00:00,Actual,Alert,Public,en-GB,Met,Severe snow warning,Future,...,"40.94,-1.62 40.94,-1.56 40.96,-1.5 40.96,-1.47...",,AEMET-Meteoalerta zona: 624401,Z_CAP_C_LEMM_20210107043640_AFAE.gz,2021,1,Enero,Invierno,23.999722,2
4,2.49.0.0.724.0.ES.20210106225001.624402NENV092...,http://www.aemet.es,2021-01-06 22:50:01+00:00,Actual,Alert,Public,es-ES,Met,Aviso de nevadas de nivel naranja,Future,...,"39.97,-1.14 40.01,-1.16 40.04,-1.08 40.06,-1.0...",,AEMET-Meteoalerta zona: 624402,Z_CAP_C_LEMM_20210107043640_AFAE.gz,2021,1,Enero,Invierno,23.999722,2

In [23]:
# Crear carpeta por meses 
import os

carpeta_salida = "avisos_aemet_por_mes"

os.makedirs(carpeta_salida, exist_ok=True)

print("Carpeta lista:", carpeta_salida)

Carpeta lista: avisos_aemet_por_mes

In [20]:
# creamos la lista de meses desde enero de 2021 hasta abril de 2026
meses_a_procesar = []

for anio in range(2021, 2027):
    for mes in range(1, 13):

        if anio == 2026 and mes > 4:
            continue

        meses_a_procesar.append((anio, mes))

print("Número de meses:", len(meses_a_procesar))
print(meses_a_procesar[:5])
print(meses_a_procesar[-5:])

Número de meses: 64
[(2021, 1), (2021, 2), (2021, 3), (2021, 4), (2021, 5)]
[(2025, 12), (2026, 1), (2026, 2), (2026, 3), (2026, 4)]

In [24]:
meses_a_procesar = []

for anio in range(2023, 2027):
    for mes in range(1, 13):

        if anio == 2023 and mes < 6:
            continue

        if anio == 2026 and mes > 4:
            continue

        meses_a_procesar.append((anio, mes))

print("Meses pendientes:", len(meses_a_procesar))
print(meses_a_procesar[:5])
print(meses_a_procesar[-5:])

Meses pendientes: 35
[(2023, 6), (2023, 7), (2023, 8), (2023, 9), (2023, 10)]
[(2025, 12), (2026, 1), (2026, 2), (2026, 3), (2026, 4)]

In [25]:
# descargar y guardar un CSV por cada mes
archivos_generados = []

for anio, mes in meses_a_procesar:

    print("=" * 80)
    print(f"PROCESANDO {anio}-{mes:02d}")
    print("=" * 80)

    # Primer y último día del mes
    fecha_inicio_mes = datetime(anio, mes, 1)

    if mes == 12:
        fecha_inicio_siguiente_mes = datetime(anio + 1, 1, 1)
    else:
        fecha_inicio_siguiente_mes = datetime(anio, mes + 1, 1)

    fecha_fin_mes = fecha_inicio_siguiente_mes - timedelta(days=1)

    # Dividir el mes en bloques de máximo 2 días
    rangos_mes = []
    fecha_actual = fecha_inicio_mes

    while fecha_actual <= fecha_fin_mes:
        inicio = fecha_actual
        fin = min(fecha_actual + timedelta(days=1), fecha_fin_mes)

        rangos_mes.append((inicio, fin))

        fecha_actual = fin + timedelta(days=1)

    print("Rangos de 2 días en este mes:", len(rangos_mes))

    dfs_mes = []

    for inicio, fin in rangos_mes:

        contenido = descargar_rango_aemet(
            inicio,
            fin,
            API_KEY,
            pausa=8,
            max_intentos=5
        )

        if contenido is None:
            print("No se pudo descargar este rango. Se pasa al siguiente.")
            continue

        df_rango = convertir_contenido_a_dataframe(contenido)

        if df_rango.empty:
            print("No se encontraron datos en este rango.")
            continue

        df_rango_limpio = limpiar_dataframe(df_rango)

        if df_rango_limpio.empty:
            print("El rango quedó vacío después de limpiar.")
            continue

        dfs_mes.append(df_rango_limpio)

        print("Filas limpias del rango:", len(df_rango_limpio))

    if len(dfs_mes) == 0:
        print(f"No se obtuvieron datos para {anio}-{mes:02d}")
        continue

    # Unir todos los rangos del mes
    df_mes = pd.concat(dfs_mes, ignore_index=True)

    # Quitar duplicados dentro del mes
    df_mes_limpio = df_mes.drop_duplicates(
        subset=[
            "identifier",
            "sent",
            "onset",
            "expires",
            "event",
            "severity",
            "area_desc",
            "headline"
        ]
    ).copy()

    print("Filas del mes antes de limpieza final:", len(df_mes))
    print("Filas del mes después de limpieza final:", len(df_mes_limpio))

    nombre_archivo = f"{carpeta_salida}/avisos_aemet_{anio}_{mes:02d}.csv"

    df_mes_limpio.to_csv(
        nombre_archivo,
        index=False,
        encoding="utf-8-sig"
    )

    archivos_generados.append(nombre_archivo)

    print("Archivo mensual guardado:", nombre_archivo)

================================================================================
PROCESANDO 2023-06
================================================================================
Rangos de 2 días en este mes: 15
Intento 1/5: 2023-06-01T00:00:00UTC → 2023-06-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11788
Intento 1/5: 2023-06-03T00:00:00UTC → 2023-06-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11264
Intento 1/5: 2023-06-05T00:00:00UTC → 2023-06-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10388
Intento 1/5: 2023-06-07T00:00:00UTC → 2023-06-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10076
Intento 1/5: 2023-06-09T00:00:00UTC → 2023-06-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10052
Intento 1/5: 2023-06-11T00:00:00UTC → 2023-06-12T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2023-06-11T00:00:00UTC → 2023-06-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10958
Intento 1/5: 2023-06-13T00:00:00UTC → 2023-06-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10188
Intento 1/5: 2023-06-15T00:00:00UTC → 2023-06-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9670
Intento 1/5: 2023-06-17T00:00:00UTC → 2023-06-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10462
Intento 1/5: 2023-06-19T00:00:00UTC → 2023-06-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10630
Intento 1/5: 2023-06-21T00:00:00UTC → 2023-06-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10482
Intento 1/5: 2023-06-23T00:00:00UTC → 2023-06-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10390
Intento 1/5: 2023-06-25T00:00:00UTC → 2023-06-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10600
Intento 1/5: 2023-06-27T00:00:00UTC → 2023-06-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10222
Intento 1/5: 2023-06-29T00:00:00UTC → 2023-06-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9984
Filas del mes antes de limpieza final: 157154
Filas del mes después de limpieza final: 109298
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_06.csv
================================================================================
PROCESANDO 2023-07
================================================================================
Rangos de 2 días en este mes: 16
Intento 1/5: 2023-07-01T00:00:00UTC → 2023-07-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9792
Intento 1/5: 2023-07-03T00:00:00UTC → 2023-07-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9794
Intento 1/5: 2023-07-05T00:00:00UTC → 2023-07-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9934
Intento 1/5: 2023-07-07T00:00:00UTC → 2023-07-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10438
Intento 1/5: 2023-07-09T00:00:00UTC → 2023-07-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11092
Intento 1/5: 2023-07-11T00:00:00UTC → 2023-07-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10802
Intento 1/5: 2023-07-13T00:00:00UTC → 2023-07-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10250
Intento 1/5: 2023-07-15T00:00:00UTC → 2023-07-16T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-07-15T00:00:00UTC → 2023-07-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10686
Intento 1/5: 2023-07-17T00:00:00UTC → 2023-07-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10742
Intento 1/5: 2023-07-19T00:00:00UTC → 2023-07-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9968
Intento 1/5: 2023-07-21T00:00:00UTC → 2023-07-22T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-07-21T00:00:00UTC → 2023-07-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9822
Intento 1/5: 2023-07-23T00:00:00UTC → 2023-07-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9700
Intento 1/5: 2023-07-25T00:00:00UTC → 2023-07-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9644
Intento 1/5: 2023-07-27T00:00:00UTC → 2023-07-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9758
Intento 1/5: 2023-07-29T00:00:00UTC → 2023-07-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10044
Intento 1/5: 2023-07-31T00:00:00UTC → 2023-07-31T23:59:59UTC
Descarga correcta
Filas limpias del rango: 6696
Filas del mes antes de limpieza final: 159162
Filas del mes después de limpieza final: 108768
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_07.csv
================================================================================
PROCESANDO 2023-08
================================================================================
Rangos de 2 días en este mes: 16
Intento 1/5: 2023-08-01T00:00:00UTC → 2023-08-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9986
Intento 1/5: 2023-08-03T00:00:00UTC → 2023-08-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9962
Intento 1/5: 2023-08-05T00:00:00UTC → 2023-08-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10430
Intento 1/5: 2023-08-07T00:00:00UTC → 2023-08-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11202
Intento 1/5: 2023-08-09T00:00:00UTC → 2023-08-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11204
Intento 1/5: 2023-08-11T00:00:00UTC → 2023-08-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10430
Intento 1/5: 2023-08-13T00:00:00UTC → 2023-08-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9946
Intento 1/5: 2023-08-15T00:00:00UTC → 2023-08-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10112
Intento 1/5: 2023-08-17T00:00:00UTC → 2023-08-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10528
Intento 1/5: 2023-08-19T00:00:00UTC → 2023-08-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11172
Intento 1/5: 2023-08-21T00:00:00UTC → 2023-08-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 12020
Intento 1/5: 2023-08-23T00:00:00UTC → 2023-08-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11060
Intento 1/5: 2023-08-25T00:00:00UTC → 2023-08-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10934
Intento 1/5: 2023-08-27T00:00:00UTC → 2023-08-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10118
Intento 1/5: 2023-08-29T00:00:00UTC → 2023-08-30T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2023-08-29T00:00:00UTC → 2023-08-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9770
Intento 1/5: 2023-08-31T00:00:00UTC → 2023-08-31T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-08-31T00:00:00UTC → 2023-08-31T23:59:59UTC
Descarga correcta
Filas limpias del rango: 7182
Filas del mes antes de limpieza final: 166056
Filas del mes después de limpieza final: 113980
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_08.csv
================================================================================
PROCESANDO 2023-09
================================================================================
Rangos de 2 días en este mes: 15
Intento 1/5: 2023-09-01T00:00:00UTC → 2023-09-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 12270
Intento 1/5: 2023-09-03T00:00:00UTC → 2023-09-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11254
Intento 1/5: 2023-09-05T00:00:00UTC → 2023-09-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 6248
Intento 1/5: 2023-09-07T00:00:00UTC → 2023-09-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9622
Intento 1/5: 2023-09-09T00:00:00UTC → 2023-09-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10076
Intento 1/5: 2023-09-11T00:00:00UTC → 2023-09-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10466
Intento 1/5: 2023-09-13T00:00:00UTC → 2023-09-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10870
Intento 1/5: 2023-09-15T00:00:00UTC → 2023-09-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10820
Intento 1/5: 2023-09-17T00:00:00UTC → 2023-09-18T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-09-17T00:00:00UTC → 2023-09-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9908
Intento 1/5: 2023-09-19T00:00:00UTC → 2023-09-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10136
Intento 1/5: 2023-09-21T00:00:00UTC → 2023-09-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9494
Intento 1/5: 2023-09-23T00:00:00UTC → 2023-09-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9376
Intento 1/5: 2023-09-25T00:00:00UTC → 2023-09-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9370
Intento 1/5: 2023-09-27T00:00:00UTC → 2023-09-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9416
Intento 1/5: 2023-09-29T00:00:00UTC → 2023-09-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9550
Filas del mes antes de limpieza final: 148876
Filas del mes después de limpieza final: 105752
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_09.csv
================================================================================
PROCESANDO 2023-10
================================================================================
Rangos de 2 días en este mes: 16
Intento 1/5: 2023-10-01T00:00:00UTC → 2023-10-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9556
Intento 1/5: 2023-10-03T00:00:00UTC → 2023-10-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9540
Intento 1/5: 2023-10-05T00:00:00UTC → 2023-10-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9624
Intento 1/5: 2023-10-07T00:00:00UTC → 2023-10-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9610
Intento 1/5: 2023-10-09T00:00:00UTC → 2023-10-10T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-10-09T00:00:00UTC → 2023-10-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9486
Intento 1/5: 2023-10-11T00:00:00UTC → 2023-10-12T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2023-10-11T00:00:00UTC → 2023-10-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9508
Intento 1/5: 2023-10-13T00:00:00UTC → 2023-10-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9570
Intento 1/5: 2023-10-15T00:00:00UTC → 2023-10-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10008
Intento 1/5: 2023-10-17T00:00:00UTC → 2023-10-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11762
Intento 1/5: 2023-10-19T00:00:00UTC → 2023-10-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11482
Intento 1/5: 2023-10-21T00:00:00UTC → 2023-10-22T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2023-10-21T00:00:00UTC → 2023-10-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10596
Intento 1/5: 2023-10-23T00:00:00UTC → 2023-10-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9918
Intento 1/5: 2023-10-25T00:00:00UTC → 2023-10-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10228
Intento 1/5: 2023-10-27T00:00:00UTC → 2023-10-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9898
Intento 1/5: 2023-10-29T00:00:00UTC → 2023-10-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10418
Intento 1/5: 2023-10-31T00:00:00UTC → 2023-10-31T23:59:59UTC
Descarga correcta
Filas limpias del rango: 7842
Filas del mes antes de limpieza final: 159046
Filas del mes después de limpieza final: 108984
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_10.csv
================================================================================
PROCESANDO 2023-11
================================================================================
Rangos de 2 días en este mes: 15
Intento 1/5: 2023-11-01T00:00:00UTC → 2023-11-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 12548
Intento 1/5: 2023-11-03T00:00:00UTC → 2023-11-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 11354
Intento 1/5: 2023-11-05T00:00:00UTC → 2023-11-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9996
Intento 1/5: 2023-11-07T00:00:00UTC → 2023-11-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9728
Intento 1/5: 2023-11-09T00:00:00UTC → 2023-11-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9660
Intento 1/5: 2023-11-11T00:00:00UTC → 2023-11-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9620
Intento 1/5: 2023-11-13T00:00:00UTC → 2023-11-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9516
Intento 1/5: 2023-11-15T00:00:00UTC → 2023-11-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9420
Intento 1/5: 2023-11-17T00:00:00UTC → 2023-11-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9426
Intento 1/5: 2023-11-19T00:00:00UTC → 2023-11-20T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-11-19T00:00:00UTC → 2023-11-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9706
Intento 1/5: 2023-11-21T00:00:00UTC → 2023-11-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9784
Intento 1/5: 2023-11-23T00:00:00UTC → 2023-11-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9536
Intento 1/5: 2023-11-25T00:00:00UTC → 2023-11-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9422
Intento 1/5: 2023-11-27T00:00:00UTC → 2023-11-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9476
Intento 1/5: 2023-11-29T00:00:00UTC → 2023-11-30T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2023-11-29T00:00:00UTC → 2023-11-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10016
Filas del mes antes de limpieza final: 149208
Filas del mes después de limpieza final: 103780
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_11.csv
================================================================================
PROCESANDO 2023-12
================================================================================
Rangos de 2 días en este mes: 16
Intento 1/5: 2023-12-01T00:00:00UTC → 2023-12-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9754
Intento 1/5: 2023-12-03T00:00:00UTC → 2023-12-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9552
Intento 1/5: 2023-12-05T00:00:00UTC → 2023-12-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9684
Intento 1/5: 2023-12-07T00:00:00UTC → 2023-12-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9740
Intento 1/5: 2023-12-09T00:00:00UTC → 2023-12-10T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-12-09T00:00:00UTC → 2023-12-10T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 3/5: 2023-12-09T00:00:00UTC → 2023-12-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9590
Intento 1/5: 2023-12-11T00:00:00UTC → 2023-12-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9670
Intento 1/5: 2023-12-13T00:00:00UTC → 2023-12-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9696
Intento 1/5: 2023-12-15T00:00:00UTC → 2023-12-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9702
Intento 1/5: 2023-12-17T00:00:00UTC → 2023-12-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9606
Intento 1/5: 2023-12-19T00:00:00UTC → 2023-12-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9664
Intento 1/5: 2023-12-21T00:00:00UTC → 2023-12-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9610
Intento 1/5: 2023-12-23T00:00:00UTC → 2023-12-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9514
Intento 1/5: 2023-12-25T00:00:00UTC → 2023-12-26T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2023-12-25T00:00:00UTC → 2023-12-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9650
Intento 1/5: 2023-12-27T00:00:00UTC → 2023-12-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9580
Intento 1/5: 2023-12-29T00:00:00UTC → 2023-12-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9588
Intento 1/5: 2023-12-31T00:00:00UTC → 2023-12-31T23:59:59UTC
Descarga correcta
Filas limpias del rango: 6372
Filas del mes antes de limpieza final: 150972
Filas del mes después de limpieza final: 103002
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2023_12.csv
================================================================================
PROCESANDO 2024-01
================================================================================
Rangos de 2 días en este mes: 16
Intento 1/5: 2024-01-01T00:00:00UTC → 2024-01-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9678
Intento 1/5: 2024-01-03T00:00:00UTC → 2024-01-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9988
Intento 1/5: 2024-01-05T00:00:00UTC → 2024-01-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10268
Intento 1/5: 2024-01-07T00:00:00UTC → 2024-01-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9796
Intento 1/5: 2024-01-09T00:00:00UTC → 2024-01-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9670
Intento 1/5: 2024-01-11T00:00:00UTC → 2024-01-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9504
Intento 1/5: 2024-01-13T00:00:00UTC → 2024-01-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9646
Intento 1/5: 2024-01-15T00:00:00UTC → 2024-01-16T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2024-01-15T00:00:00UTC → 2024-01-16T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 3/5: 2024-01-15T00:00:00UTC → 2024-01-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10446
Intento 1/5: 2024-01-17T00:00:00UTC → 2024-01-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10644
Intento 1/5: 2024-01-19T00:00:00UTC → 2024-01-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10168
Intento 1/5: 2024-01-21T00:00:00UTC → 2024-01-22T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9684
Intento 1/5: 2024-01-23T00:00:00UTC → 2024-01-24T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9738
Intento 1/5: 2024-01-25T00:00:00UTC → 2024-01-26T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9632
Intento 1/5: 2024-01-27T00:00:00UTC → 2024-01-28T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9452
Intento 1/5: 2024-01-29T00:00:00UTC → 2024-01-30T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9436
Intento 1/5: 2024-01-31T00:00:00UTC → 2024-01-31T23:59:59UTC
Descarga correcta
Filas limpias del rango: 6288
Filas del mes antes de limpieza final: 154038
Filas del mes después de limpieza final: 105134
Archivo mensual guardado: avisos_aemet_por_mes/avisos_aemet_2024_01.csv
================================================================================
PROCESANDO 2024-02
================================================================================
Rangos de 2 días en este mes: 15
Intento 1/5: 2024-02-01T00:00:00UTC → 2024-02-02T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9418
Intento 1/5: 2024-02-03T00:00:00UTC → 2024-02-04T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9412
Intento 1/5: 2024-02-05T00:00:00UTC → 2024-02-06T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9710
Intento 1/5: 2024-02-07T00:00:00UTC → 2024-02-08T23:59:59UTC
Error 500 en AEMET. Esperando y reintentando...
Intento 2/5: 2024-02-07T00:00:00UTC → 2024-02-08T23:59:59UTC
Descarga correcta
Filas limpias del rango: 10418
Intento 1/5: 2024-02-09T00:00:00UTC → 2024-02-10T23:59:59UTC
Demasiadas peticiones. Esperando 90 segundos...
Intento 2/5: 2024-02-09T00:00:00UTC → 2024-02-10T23:59:59UTC
Descarga correcta
Filas limpias del rango: 7352
Intento 1/5: 2024-02-11T00:00:00UTC → 2024-02-12T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9756
Intento 1/5: 2024-02-13T00:00:00UTC → 2024-02-14T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9528
Intento 1/5: 2024-02-15T00:00:00UTC → 2024-02-16T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9564
Intento 1/5: 2024-02-17T00:00:00UTC → 2024-02-18T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9588
Intento 1/5: 2024-02-19T00:00:00UTC → 2024-02-20T23:59:59UTC
Descarga correcta
Filas limpias del rango: 9624

In [26]:
# comprobar archivos mensuales generados
print("Número de archivos mensuales generados:", len(archivos_generados))

archivos_generados[:10]

Número de archivos mensuales generados: 35

['avisos_aemet_por_mes/avisos_aemet_2023_06.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_07.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_08.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_09.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_10.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_11.csv',
 'avisos_aemet_por_mes/avisos_aemet_2023_12.csv',
 'avisos_aemet_por_mes/avisos_aemet_2024_01.csv',
 'avisos_aemet_por_mes/avisos_aemet_2024_02.csv',
 'avisos_aemet_por_mes/avisos_aemet_2024_03.csv']

In [32]:

import glob

archivos_generados = sorted(glob.glob("avisos_aemet_por_mes/*.csv"))

print("Archivos encontrados:", len(archivos_generados))

Archivos encontrados: 64

In [38]:
# definimos las columnas 
columnas_utiles = [
    "identifier",
    "sent",
    "onset",
    "expires",
    "año",
    "mes",
    "mes_num",
    "estacion",
    "event",
    "severity",
    "riesgo_numerico",
    "duracion_horas",
    "area_desc",
    "polygon",
    "geocode",
    "headline",
    "description"
]

columnas_duplicados = [
    "identifier",
    "sent",
    "onset",
    "expires",
    "event",
    "severity",
    "area_desc",
    "headline"
]

In [39]:
archivo_final = "avisos_aemet_2021_2026_reducido_tableau.csv"

# Si ya existe, lo borramos para empezar limpio
if os.path.exists(archivo_final):
    os.remove(archivo_final)

primera_vez = True
total_filas_guardadas = 0

for archivo in archivos_generados:
    print("=" * 80)
    print("Procesando:", archivo)
    print("=" * 80)

    try:
        lector = pd.read_csv(
            archivo,
            chunksize=50000,
            encoding="utf-8-sig",
            low_memory=False
        )

        for i, chunk in enumerate(lector):
            print(f"  Bloque {i + 1}")

            # Nos quedamos solo con las columnas útiles que existan
            columnas_disponibles = [
                col for col in columnas_utiles
                if col in chunk.columns
            ]

            chunk = chunk[columnas_disponibles]

            # Quitamos duplicados dentro del bloque
            columnas_dup_disponibles = [
                col for col in columnas_duplicados
                if col in chunk.columns
            ]

            chunk = chunk.drop_duplicates(
                subset=columnas_dup_disponibles
            )

            # Guardamos el bloque en el archivo final
            chunk.to_csv(
                archivo_final,
                mode="w" if primera_vez else "a",
                header=primera_vez,
                index=False,
                encoding="utf-8-sig"
            )

            primera_vez = False
            total_filas_guardadas += len(chunk)

            print("  Filas añadidas:", len(chunk))
            print("  Total acumulado:", total_filas_guardadas)

    except Exception as e:
        print("ERROR leyendo archivo:")
        print(archivo)
        print(e)
        continue

print("Proceso terminado")
print("CSV final creado:", archivo_final)
print("Filas guardadas aproximadamente:", total_filas_guardadas)

================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_01.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 50000
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 100000
  Bloque 3
  Filas añadidas: 17594
  Total acumulado: 117594
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_02.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 167594
  Bloque 2
  Filas añadidas: 46816
  Total acumulado: 214410
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_03.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 264410
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 314410
  Bloque 3
  Filas añadidas: 2336
  Total acumulado: 316746
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_04.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 366746
  Bloque 2
  Filas añadidas: 49180
  Total acumulado: 415926
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_05.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 465926
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 515926
  Bloque 3
  Filas añadidas: 2576
  Total acumulado: 518502
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_06.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 568502
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 618502
  Bloque 3
  Filas añadidas: 3276
  Total acumulado: 621778
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_07.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 671778
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 721778
  Bloque 3
  Filas añadidas: 6642
  Total acumulado: 728420
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_08.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 778420
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 828420
  Bloque 3
  Filas añadidas: 10090
  Total acumulado: 838510
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_09.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 888510
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 938510
  Bloque 3
  Filas añadidas: 3658
  Total acumulado: 942168
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_10.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 992168
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1042168
  Bloque 3
  Filas añadidas: 2786
  Total acumulado: 1044954
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_11.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1094954
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1144954
  Bloque 3
  Filas añadidas: 3580
  Total acumulado: 1148534
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2021_12.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1198534
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1248534
  Bloque 3
  Filas añadidas: 6680
  Total acumulado: 1255214
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_01.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1305214
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1355214
  Bloque 3
  Filas añadidas: 7212
  Total acumulado: 1362426
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_02.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1412426
  Bloque 2
  Filas añadidas: 43226
  Total acumulado: 1455652
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_03.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1505652
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1555652
  Bloque 3
  Filas añadidas: 7222
  Total acumulado: 1562874
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_04.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1612874
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1662874
  Bloque 3
  Filas añadidas: 568
  Total acumulado: 1663442
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_05.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1713442
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1763442
  Bloque 3
  Filas añadidas: 2354
  Total acumulado: 1765796
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_06.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1815796
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1865796
  Bloque 3
  Filas añadidas: 4154
  Total acumulado: 1869950
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_07.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 1919950
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 1969950
  Bloque 3
  Filas añadidas: 14414
  Total acumulado: 1984364
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_08.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2034364
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2084364
  Bloque 3
  Filas añadidas: 9524
  Total acumulado: 2093888
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_09.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2143888
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2193888
  Bloque 3
  Filas añadidas: 1992
  Total acumulado: 2195880
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_10.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2245880
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2295880
  Bloque 3
  Filas añadidas: 1166
  Total acumulado: 2297046
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_11.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2347046
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2397046
  Bloque 3
  Filas añadidas: 2284
  Total acumulado: 2399330
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2022_12.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2449330
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2499330
  Bloque 3
  Filas añadidas: 5820
  Total acumulado: 2505150
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_01.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2555150
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2605150
  Bloque 3
  Filas añadidas: 10216
  Total acumulado: 2615366
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_02.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2665366
  Bloque 2
  Filas añadidas: 48490
  Total acumulado: 2713856
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_03.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2763856
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 2813856
  Bloque 3
  Filas añadidas: 3586
  Total acumulado: 2817442
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_04.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2867442
  Bloque 2
  Filas añadidas: 48850
  Total acumulado: 2916292
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_05.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 2966292
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3016292
  Bloque 3
  Filas añadidas: 7240
  Total acumulado: 3023532
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_06.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3073532
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3123532
  Bloque 3
  Filas añadidas: 9298
  Total acumulado: 3132830
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_07.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3182830
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3232830
  Bloque 3
  Filas añadidas: 8768
  Total acumulado: 3241598
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_08.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3291598
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3341598
  Bloque 3
  Filas añadidas: 13980
  Total acumulado: 3355578
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_09.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3405578
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3455578
  Bloque 3
  Filas añadidas: 5752
  Total acumulado: 3461330
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_10.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3511330
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3561330
  Bloque 3
  Filas añadidas: 8984
  Total acumulado: 3570314
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_11.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3620314
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3670314
  Bloque 3
  Filas añadidas: 3780
  Total acumulado: 3674094
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2023_12.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3724094
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3774094
  Bloque 3
  Filas añadidas: 3002
  Total acumulado: 3777096
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_01.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3827096
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3877096
  Bloque 3
  Filas añadidas: 5134
  Total acumulado: 3882230
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_02.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 3932230
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 3982230
  Bloque 3
  Filas añadidas: 636
  Total acumulado: 3982866
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_03.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4032866
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4082866
  Bloque 3
  Filas añadidas: 7716
  Total acumulado: 4090582
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_04.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4140582
  Bloque 2
  Filas añadidas: 48770
  Total acumulado: 4189352
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_05.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4239352
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4289352
  Bloque 3
  Filas añadidas: 1662
  Total acumulado: 4291014
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_06.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4341014
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4391014
  Bloque 3
  Filas añadidas: 3020
  Total acumulado: 4394034
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_07.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4444034
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4494034
  Bloque 3
  Filas añadidas: 9732
  Total acumulado: 4503766
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_08.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4553766
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4603766
  Bloque 3
  Filas añadidas: 11074
  Total acumulado: 4614840
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_09.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4664840
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4714840
  Bloque 3
  Filas añadidas: 3130
  Total acumulado: 4717970
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_10.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4767970
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4817970
  Bloque 3
  Filas añadidas: 10066
  Total acumulado: 4828036
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_11.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4878036
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 4928036
  Bloque 3
  Filas añadidas: 3302
  Total acumulado: 4931338
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2024_12.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 4981338
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 5031338
  Bloque 3
  Filas añadidas: 6818
  Total acumulado: 5038156
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2025_01.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 5088156
  Bloque 2
  Filas añadidas: 50000
  Total acumulado: 5138156
  Bloque 3
  Filas añadidas: 9256
  Total acumulado: 5147412
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2025_02.csv
================================================================================
  Bloque 1
  Filas añadidas: 50000
  Total acumulado: 5197412
  Bloque 2
  Filas añadidas: 42446
  Total acumulado: 5239858
================================================================================
Procesando: avisos_aemet_por_mes\avisos_aemet_2025_03.csv

In [40]:
df_muestra = pd.read_csv(
    "avisos_aemet_2021_2026_reducido_tableau.csv",
    nrows=1000,
    encoding="utf-8-sig"
)

print(df_muestra.shape)
df_muestra.head()

(1000, 17)

,identifier,sent,onset,expires,año,mes,mes_num,estacion,event,severity,riesgo_numerico,duracion_horas,area_desc,polygon,geocode,headline,description
0,2.49.0.0.724.0.ES.20210101064907.610401VIRM012...,2021-01-01 06:49:07+00:00,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,13.999722,Valle del Almanzora y Los Vélez,"37.92,-2.21 37.89,-2.17 37.9,-2.12 37.88,-2.1 ...",AEMET-Meteoalerta zona: 610401,Aviso de vientos de nivel amarillo. Valle del ...,Rachas máximas: 70 km/h. Vientos del oeste
1,2.49.0.0.724.0.ES.20210101064907.610401VIRM012...,2021-01-01 06:49:07+00:00,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Moderate wind warning,Moderate,1,13.999722,Valle del Almanzora y Los Vélez,"37.92,-2.21 37.89,-2.17 37.9,-2.12 37.88,-2.1 ...",AEMET-Meteoalerta zona: 610401,Moderate wind warning. Valle del Almanzora y L...,Maximum gust of wind: 70 km/h. Vientos del oeste
2,2.49.0.0.724.0.ES.20210101064907.610402VIRM012...,2021-01-01 06:49:07+00:00,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,13.999722,Nacimiento y Campo de Tabernas,"37.1,-2.95 37.16,-2.93 37.17,-2.89 37.23,-2.87...",AEMET-Meteoalerta zona: 610402,Aviso de vientos de nivel amarillo. Nacimiento...,Rachas máximas: 70 km/h. Vientos del oeste
3,2.49.0.0.724.0.ES.20210101064907.610402VIRM012...,2021-01-01 06:49:07+00:00,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Moderate wind warning,Moderate,1,13.999722,Nacimiento y Campo de Tabernas,"37.1,-2.95 37.16,-2.93 37.17,-2.89 37.23,-2.87...",AEMET-Meteoalerta zona: 610402,Moderate wind warning. Nacimiento y Campo de T...,Maximum gust of wind: 70 km/h. Vientos del oeste
4,2.49.0.0.724.0.ES.20210101064907.610403VIRM012...,2021-01-01 06:49:07+00:00,2021-01-01 06:00:00+00:00,2021-01-01 20:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,14.999722,Poniente y Almería Capital,"36.75,-3.13 36.79,-3.14 36.84,-3.03 36.92,-3.0...",AEMET-Meteoalerta zona: 610403,Aviso de vientos de nivel amarillo. Poniente y...,Rachas máximas: 70 km/h. Vientos del oeste

In [41]:
df_muestra.columns.tolist()

['identifier',
 'sent',
 'onset',
 'expires',
 'año',
 'mes',
 'mes_num',
 'estacion',
 'event',
 'severity',
 'riesgo_numerico',
 'duracion_horas',
 'area_desc',
 'polygon',
 'geocode',
 'headline',
 'description']

In [42]:
df_muestra[["onset", "expires", "event", "severity", "area_desc"]].head(20)

,onset,expires,event,severity,area_desc
0,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,Aviso de vientos de nivel amarillo,Moderate,Valle del Almanzora y Los Vélez
1,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,Moderate wind warning,Moderate,Valle del Almanzora y Los Vélez
2,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,Aviso de vientos de nivel amarillo,Moderate,Nacimiento y Campo de Tabernas
3,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,Moderate wind warning,Moderate,Nacimiento y Campo de Tabernas
4,2021-01-01 06:00:00+00:00,2021-01-01 20:59:59+00:00,Aviso de vientos de nivel amarillo,Moderate,Poniente y Almería Capital
5,2021-01-01 06:00:00+00:00,2021-01-01 20:59:59+00:00,Moderate wind warning,Moderate,Poniente y Almería Capital
6,2021-01-01 06:00:00+00:00,2021-01-01 18:59:59+00:00,Aviso de vientos de nivel amarillo,Moderate,Costa granadina
7,2021-01-01 06:00:00+00:00,2021-01-01 18:59:59+00:00,Moderate wind warning,Moderate,Costa granadina
8,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Aviso de temperaturas mínimas de nivel naranja,Severe,Pirineo oscense
9,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Severe low-temperature warning,Severe,Pirineo oscense
10,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Aviso de temperaturas mínimas de nivel naranja,Severe,Pirineo de Girona
11,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Severe low-temperature warning,Severe,Pirineo de Girona
12,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Aviso de temperaturas mínimas de nivel naranja,Severe,Valle de Arán
13,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Severe low-temperature warning,Severe,Valle de Arán
14,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Aviso de temperaturas mínimas de nivel naranja,Severe,Pirineo de Lleida
15,2021-01-02 23:00:00+00:00,2021-01-03 07:59:59+00:00,Severe low-temperature warning,Severe,Pirineo de Lleida
16,2021-01-02 23:00:00+00:00,2021-01-03 16:59:59+00:00,Aviso de nevadas de nivel amarillo,Moderate,Suroccidental asturiana
17,2021-01-02 23:00:00+00:00,2021-01-03 16:59:59+00:00,Moderate snow warning,Moderate,Suroccidental asturiana
18,2021-01-02 23:00:00+00:00,2021-01-03 16:59:59+00:00,Aviso de nevadas de nivel amarillo,Moderate,Central y Valles Mineros
19,2021-01-02 23:00:00+00:00,2021-01-03 16:59:59+00:00,Moderate snow warning,Moderate,Central y Valles Mineros

In [43]:
archivo_ligero = "avisos_aemet_2021_2026_tableau_ligero.csv"

columnas_ligeras = [
    "identifier",
    "sent",
    "onset",
    "expires",
    "año",
    "mes",
    "mes_num",
    "estacion",
    "event",
    "severity",
    "riesgo_numerico",
    "duracion_horas",
    "area_desc",
    "geocode"
]

if os.path.exists(archivo_ligero):
    os.remove(archivo_ligero)

primera_vez = True
total_filas_ligero = 0

lector = pd.read_csv(
    "avisos_aemet_2021_2026_reducido_tableau.csv",
    chunksize=50000,
    encoding="utf-8-sig",
    low_memory=False
)

for i, chunk in enumerate(lector):
    print(f"Procesando bloque {i + 1}")

    columnas_disponibles = [
        col for col in columnas_ligeras
        if col in chunk.columns
    ]

    chunk = chunk[columnas_disponibles]

    chunk.to_csv(
        archivo_ligero,
        mode="w" if primera_vez else "a",
        header=primera_vez,
        index=False,
        encoding="utf-8-sig"
    )

    primera_vez = False
    total_filas_ligero += len(chunk)

print("CSV ligero creado:", archivo_ligero)
print("Filas:", total_filas_ligero)

Procesando bloque 1
Procesando bloque 2
Procesando bloque 3
Procesando bloque 4
Procesando bloque 5
Procesando bloque 6
Procesando bloque 7
Procesando bloque 8
Procesando bloque 9
Procesando bloque 10
Procesando bloque 11
Procesando bloque 12
Procesando bloque 13
Procesando bloque 14
Procesando bloque 15
Procesando bloque 16
Procesando bloque 17
Procesando bloque 18
Procesando bloque 19
Procesando bloque 20
Procesando bloque 21
Procesando bloque 22
Procesando bloque 23
Procesando bloque 24
Procesando bloque 25
Procesando bloque 26
Procesando bloque 27
Procesando bloque 28
Procesando bloque 29
Procesando bloque 30
Procesando bloque 31
Procesando bloque 32
Procesando bloque 33
Procesando bloque 34
Procesando bloque 35
Procesando bloque 36
Procesando bloque 37
Procesando bloque 38
Procesando bloque 39
Procesando bloque 40
Procesando bloque 41
Procesando bloque 42
Procesando bloque 43
Procesando bloque 44
Procesando bloque 45
Procesando bloque 46
Procesando bloque 47
Procesando bloque 48
Procesando bloque 49
Procesando bloque 50
Procesando bloque 51
Procesando bloque 52
Procesando bloque 53
Procesando bloque 54
Procesando bloque 55
Procesando bloque 56
Procesando bloque 57
Procesando bloque 58
Procesando bloque 59
Procesando bloque 60
Procesando bloque 61
Procesando bloque 62
Procesando bloque 63
Procesando bloque 64
Procesando bloque 65
Procesando bloque 66
Procesando bloque 67
Procesando bloque 68
Procesando bloque 69
Procesando bloque 70
Procesando bloque 71
Procesando bloque 72
Procesando bloque 73
Procesando bloque 74
Procesando bloque 75
Procesando bloque 76
Procesando bloque 77
Procesando bloque 78
Procesando bloque 79
Procesando bloque 80
Procesando bloque 81
Procesando bloque 82
Procesando bloque 83
Procesando bloque 84
Procesando bloque 85
Procesando bloque 86
Procesando bloque 87
Procesando bloque 88
Procesando bloque 89
Procesando bloque 90
Procesando bloque 91
Procesando bloque 92
Procesando bloque 93
Procesando bloque 94
Procesando bloque 95
Procesando bloque 96
Procesando bloque 97
Procesando bloque 98
Procesando bloque 99
Procesando bloque 100
Procesando bloque 101
Procesando bloque 102
Procesando bloque 103
Procesando bloque 104
Procesando bloque 105
Procesando bloque 106
Procesando bloque 107
Procesando bloque 108
Procesando bloque 109
Procesando bloque 110
Procesando bloque 111
Procesando bloque 112
Procesando bloque 113
Procesando bloque 114
Procesando bloque 115
Procesando bloque 116
Procesando bloque 117
Procesando bloque 118
Procesando bloque 119
Procesando bloque 120
Procesando bloque 121
Procesando bloque 122
Procesando bloque 123
Procesando bloque 124
Procesando bloque 125
Procesando bloque 126
Procesando bloque 127
Procesando bloque 128
Procesando bloque 129
Procesando bloque 130
Procesando bloque 131
Procesando bloque 132
Procesando bloque 133
Procesando bloque 134
Procesando bloque 135
CSV ligero creado: avisos_aemet_2021_2026_tableau_ligero.csv
Filas: 6738600

In [44]:


archivo = "avisos_aemet_2021_2026_reducido_tableau.csv"

total_filas = 0
columnas = None

for chunk in pd.read_csv(
    archivo,
    chunksize=50000,
    encoding="utf-8-sig",
    low_memory=False
):
    total_filas += len(chunk)
    
    if columnas is None:
        columnas = chunk.columns.tolist()

print("Filas:", total_filas)
print("Columnas:", len(columnas))
print("Nombres de columnas:")
print(columnas)

Filas: 6738600
Columnas: 17
Nombres de columnas:
['identifier', 'sent', 'onset', 'expires', 'año', 'mes', 'mes_num', 'estacion', 'event', 'severity', 'riesgo_numerico', 'duracion_horas', 'area_desc', 'polygon', 'geocode', 'headline', 'description']